### ISSUE TITLE
About button triggering heuristic security on kaspersky

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#257]
Clicking on the about button drops me a heuristic analysis warning of https://js41637.github.io/Overwatch-Item-Tracker/templates/modals/about.html . I checked the code myself and have no real idea why it's doing it nor the security suite is giving me any details.

Honestly is not a big hassle or anything, just thought you should know.

**Comment by Js41637** [comment]
I have no idea, there's no code there, it's just a HTML template loaded by angular.

**Comment by Js41637** [comment]
I assume this was caused by one of the links using `http` instead of `https` which was fixed in pr #258

**Comment by slowthgt** [comment]
Still throws the alerts, but I'll do my own investigations first

**Comment by slowthgt** [comment]
Sorry for the necro, but seems to have fixed itself.
